# tasks file for packer-template
---
- block:
    - include: metadata.yml
    - include: update.yml
    - include: ssh-server.yml
    - include: networking.yml
    - include: vagrant.yml
    - include: reboot.yml
  when: packer_template_state == 'pre'
  tags:
    - configuration
    - packer-template
    - packer-template-pre

- block:
    - include: virtualbox.yml
    - include: cleanup.yml
  when: packer_template_state == 'post'
  tags:
    - configuration
    - packer-template
    - packer-template-post
