# tasks file for packer-template
---
- block:
    - include: tasks/metadata.yml
    - include: tasks/update.yml
    - include: tasks/ssh-server.yml
    - include: tasks/networking.yml
    - include: tasks/vagrant.yml
    - include: tasks/reboot.yml
  when: packer_template_state == 'pre'
  tags:
    - configuration
    - packer-template
    - packer-template-pre

- block:
    - include: tasks/virtualbox.yml
    - include: tasks/cleanup.yml
  when: packer_template_state == 'post'
  tags:
    - configuration
    - packer-template
    - packer-template-post
