# tasks file
---
- name: pre
  when: packer_template_state == 'pre'
  tags:
    - configuration
    - packer-template
    - packer-template-pre
  block:
    - ansible.builtin.import_tasks: metadata.yml
    - ansible.builtin.import_tasks: update.yml
    - ansible.builtin.import_tasks: ssh-server.yml
    - ansible.builtin.import_tasks: networking.yml
    - ansible.builtin.import_tasks: vagrant.yml
    - ansible.builtin.import_tasks: systemd.yml
    - ansible.builtin.import_tasks: reboot.yml

- name: post
  when: packer_template_state == 'post'
  tags:
    - configuration
    - packer-template
    - packer-template-post
  block:
    - ansible.builtin.import_tasks: virtualbox.yml
    - ansible.builtin.import_tasks: cleanup.yml
