# tasks file
---
- name: metadata | add
  ansible.builtin.copy:
    content: "{{ packer_template_metadata | to_json }}"
    dest: /etc/packer-metadata.json
    owner: root
    group: root
    mode: 0444
